### ISSUE TITLE
~/.fonts/ is deprecated for user fonts; fnt should use the proper XDG directory

### ISSUE THREAD

**Issue by janc13** [alexmyczko/fnt#15]
the default `/etc/fonts/fonts.conf` has:

```
<!-- Font directory list -->

        <dir>/usr/share/fonts</dir>
        <dir>/usr/local/share/fonts</dir>
        <dir prefix="xdg">fonts</dir>
        <!-- the following element will be removed in the future -->
        <dir>~/.fonts</dir>
```

As you can see, `~/.fonts/` is deprecated now, and it should be whatever XDG environment variables point to (or `~/.local/share/fonts/` by default).

**Comment by alexmyczko** [comment]
that `/etc/fonts/fonts.conf` comes with `https://tracker.debian.org/pkg/fontconfig`, looking at the version in sid, and then at the versions from archive.d.o: https://sid.ethz.ch/debian/fnt/fc/ around 2014 with version 2.11 that warning as comment was added. it'll take how many more decades of year to happen? is there plan timeline somewhere?

**Comment by alexmyczko** [comment]
what's that XDG variable called exactly? i'm having trouble finding it...

grep ".local/share" -ri /etc 2>/dev/null |grep font 
/etc/apparmor.d/abstractions/fonts:  owner @{HOME}/.local/share/fonts/     r,
/etc/apparmor.d/abstractions/fonts:  owner @{HOME}/.local/share/fonts/**   r,
/etc/apparmor.d/abstractions/fonts:  /usr/local/share/fonts/               r,
/etc/apparmor.d/abstractions/fonts:  /usr/local/share/fonts/**             r,
/etc/fonts/fonts.conf:	<dir>/usr/local/share/fonts</dir>

**Comment by janc13** [comment]
The variable to use is indeed `XDG_DATA_HOME` (or assume it’s `$HOME/.local/share` if that doesn't exist).

So `${XDG_DATA_HOME:-$HOME/.local/share}/fonts`

(And sorry for answering this late.)

**Comment by alexmyczko** [comment]
if XDG_DATA_HOME does not exist, does macOS or any BSD or non-linux system propose .local/share instead of a .dir directly?

**Comment by Tachi107** [comment]
> if XDG_DATA_HOME does not exist, does macOS or any BSD or non-linux system propose .local/share instead of a .dir directly?

I doubt this is relevant for macOS, as fnt doesn't use `$HOME/.fonts` on that platform.

[FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=fonts-conf&sektion=5&format=html) uses the XDG directory too

![image](https://user-images.githubusercontent.com/34214253/157980576-c30b434d-bea3-455e-ae29-908874400ae8.png)

And looking at the [`fonts-conf(5)`](https://man.openbsd.org/fonts.conf.5) man page this also seems true for OpenBSD
