### ISSUE TITLE
Comparison with homebrew-cask-fonts

### ISSUE THREAD

**Issue by vladimyr** [alexmyczko/fnt#2]
You said the following in your rationale section:

> If you run macOS, neither fink, brew, nor macports come with a great list of available to install fonts.

I never used fink and didn't use MacPorts for font management but I certainly do use https://github.com/Homebrew/homebrew-cask-fonts According to GitHub's listing it contains roughly 1700 different fonts all installable by using established HB/HB Cask workflow. I don't know about you but that certainly fits my _great list_ standards 😄 
Now for the honest question: Am I missing something here that makes fnt better choice compared to it, or you somehow managed to miss its existence? 🤔 

Nevertheless, I very much like the idea and simple and effective cross-platform implementation. 👍

**Comment by alexmyczko** [comment]
> You said the following in your rationale section:
> 
> > If you run macOS, neither fink, brew, nor macports come with a great list of available to install fonts.
> 
> I never used fink and didn't use MacPorts for font management but I certainly do use https://github.com/Homebrew/homebrew-cask-fonts According to GitHub's listing it contains roughly 1700 different fonts all installable by using established HB/HB Cask workflow. I don't know about you but that certainly fits my _great list_ standards 😄

I was aware of it, however when I tried to install the Agave font, the package was broken, I only had one instead of Bold+Regular. And I didn't check right now, but OCR-A and OCR-B were missing too, so it's just complementary.

I might add some more sources to it, so it'll definitely be an enrichment. And it's not just for macOS, but also
Haiku OS, and pretty much any Linux distribution (stable of Debian has very old, or not the newest fonts) for example.

> Now for the honest question: Am I missing something here that makes fnt better choice compared to it, or you somehow managed to miss its existence? 🤔

No, unless you encounter bugs in packaged homebrew fonts, or missing them in their repository.

> Nevertheless, I very much like the idea and simple and effective cross-platform implementation. 👍

Thank you! :)

**Comment by vladimyr** [comment]
Thanks for your response :+1: 

> I was aware of it, however when I tried to install the Agave font, the package was broken, I only had one instead of Bold+Regular.

I see only Agave patched by Nerd Fonts: https://github.com/Homebrew/homebrew-cask-fonts/blob/742affa/Casks/font-agave-nerd-font.rb I guess you meant https://github.com/blobject/agave instead? FWIW it is fairly easy to update an existing cask or contribute a new one.

> And I didn't check right now, but OCR-A and OCR-B were missing too, so it's just complementary.

OCR family is available: https://github.com/Homebrew/homebrew-cask-fonts/blob/742affa/Casks/font-ocr.rb

> And it's not just for macOS, but also
> Haiku OS, and pretty much any Linux distribution (stable of Debian has very old, or not the newest fonts) for example.

I get that, and I wholeheartedly believe it truly shines there due to the reasons you already explained. I wasn't questioning that at all, in fact, I'm going to use it on my Linux devices. I just found strange your HB dismissal :shrug:

Well, you answered my question so I guess it is time to close this :tada:
