### ISSUE TITLE
dependency/ install information missing?

### ISSUE THREAD

**Issue by jarrettone** [alexmyczko/fnt#26]
I get `line 175: unxz: command not found` when running `fnt search some_font`. It still finds what I'm looking for, but it prints this error. Because it found it, I'm assuming, its either not a critical dependency or I'm missing some results or something. I was able to find `xz` in Homebrew and this clears up the error.

I feel it would be nice to have a mention of the dependency in the REAME.md. Would you like to have such a mention? If so, would you prefer to add it yourself or would you want a Pull request for it?

I will also look to add `xz` to the Homebrew formula [here](https://github.com/Homebrew/homebrew-core/blob/1c7871ab9e6acbf5d270d36f9cce9fbe7881e3e4/Formula/fnt.rb#L18) to get Homebrew to take care of this dependency when installing `fnt` with `brew install fnt` on the systems it supports.

**Comment by alexmyczko** [comment]
yes the homebrew formula needs the depends on xz definitely. thank you for adding a atch for it

**Comment by alexmyczko** [comment]
since this appears to be an issue for two or more people i will consider adding the info in a more compact way than suggested at https://github.com/alexmyczko/fnt/issues/24

**Comment by alexmyczko** [comment]
xz is needed to access the ~500 fonts from debian sid.

**Comment by alexmyczko** [comment]
Dependencies are documented here: https://packages.debian.org/sid/fnt
