### ISSUE TITLE
http://bootes.ethz.ch/fonts/ is down

### ISSUE THREAD

**Issue by mochaaP** [alexmyczko/fnt#28]
The webserver hosting prebuilt distro packages is down (80, 443 is not listening), seems only SSH is open. Could you check that? Thank you :)

**Comment by alexmyczko** [comment]
That webserver only hosts previews of google fonts, well not anymore at the moment. The fonts themselves are hosted from another server, so all fonts can be installed there are just no previews for the google ones…

**Comment by mochaaP** [comment]
I'm looking for the RPM packages. Can you post a link here?

**Comment by alexmyczko** [comment]
sorry cant find it atm but i used https://manpages.debian.org/testing/equivs/equivs-build.1.en.html and alien to create the rpms...

**Comment by alexmyczko** [comment]
haha i found it! going to revive RSN(tm)

**Comment by alexmyczko** [comment]
http://sid.ethz.ch/fonts/ (will need to fix urls, and stuff, but it's restoring there, rsync still running, but already works)

**Comment by Gitoffthelawn** [comment]
The new host appears to be down.  Please see https://github.com/alexmyczko/fnt/issues/67
