### ISSUE TITLE
apt version of fnt is outdated, causing weird behaviour

### ISSUE THREAD

**Issue by MinekPo1** [alexmyczko/fnt#32]
yeah umm what

**Comment by MinekPo1** [comment]
ah, it seems the version on `apt` is old and does not have the condition on [fnt:146-150](https://github.com/alexmyczko/fnt/blob/91654bd608c5220dfbf24930e119184b305be76d/fnt#L146C3-L150C5), leaving this issue open to help others who fall into this pitfall and inform that the apt version is outdated

**Comment by alexmyczko** [comment]
I'm not sure I understand? What OS/version do you exactly have? And what are you running and expecting and recieving?

**Comment by MinekPo1** [comment]
Oh sorry, seems like the issue is with my system, at 1.5.1 is in fact available on apt. No idea what is going on, so closing.

Again sorry :/
