### ISSUE TITLE
Please report OpenBSD to https://github.com/alexmyczko/fnt/issues

### ISSUE THREAD

**Issue by anoduck** [alexmyczko/fnt#33]
Honestly, I thought I already had this up and running, guess not. Obviously, it would be nice if this project supported OpenBSD. It appears to already support FreeBSD, which is not too different to make compatibility a gargantuan obstacle.

**Comment by alexmyczko** [comment]
Well could you check if it works on OpenBSD? Can you package it for it?

**Comment by anoduck** [comment]
@alexmyczko Will see, will see.

- I can't remember what the package manager is for NetBSD, been a few years.
- Chafa is a go. `sudo pkg_add -U chafa`
- `fnt -l` works.
- ROFL... `fnt -h`... "Nothing..."
- `fnt -i` works from being tested with victormono.
- `fnt info` works as well.

Pushing changes

**Comment by anoduck** [comment]
Pull request: https://github.com/alexmyczko/fnt/pull/34

**Comment by alexmyczko** [comment]
I guess we can close this now?
